services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        application_name: myApp
    container_name: my_app
    environment:
      - APP_NAME=myApp
      - ./h2data:/opt/h2data
    ports:
      - "8080:8080"
