apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: dev
spec:
  selector:
    app: symmetricds
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080