apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: dev
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: "/srv/nfs"
    server: 192.168.100.20