apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
        - name: pg-symmetricds-store
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "mydb"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: pg-username
                  name: pg-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pg-password
                  name: pg-secret



